import type { QueryPlan } from '@/types/query'

/* ─────────────  SQL compilation (Postgres / MySQL / DuckDB)  ───────────── */

function quoteIdent(name: string): string {
  // Split dotted paths (table.column) and quote each segment separately.
  return name
    .split('.')
    .map((part) => `"${part.replace(/"/g, '""')}"`)
    .join('.')
}

// Whitelist of SQL expressions the planner may emit as raw (e.g. date arithmetic).
// These never contain user input; they are generated by the LLM from a fixed schema.
const RAW_SQL_EXPR =
  /^\s*(now\(\)|current_date|current_timestamp|current_time|date_trunc\s*\(|date\s*\(|extract\s*\(|interval\s)/i
const RAW_SQL_COMPOUND =
  /^\s*(now\(\)|current_date|current_timestamp|date_trunc\([^)]*\))\s*[-+]\s*interval\s+'[^']+'\s*$/i

function isRawSqlExpression(value: unknown): value is string {
  if (typeof value !== 'string') return false
  return RAW_SQL_COMPOUND.test(value) || RAW_SQL_EXPR.test(value)
}

function quoteValue(value: unknown): string {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE'
  if (Array.isArray(value)) return `(${value.map(quoteValue).join(', ')})`
  if (isRawSqlExpression(value)) return value
  return `'${String(value).replace(/'/g, "''")}'`
}

function selectClause(plan: QueryPlan): string {
  const aggMap: Record<string, string> = {
    sum: 'SUM',
    avg: 'AVG',
    count: 'COUNT',
    min: 'MIN',
    max: 'MAX',
  }

  const cols: string[] = []

  if (plan.timeBucket) {
    const { field, unit, alias } = plan.timeBucket
    const expr = `DATE_TRUNC('${unit}', ${quoteIdent(field)})`
    cols.push(`${expr} AS ${quoteIdent(alias ?? unit)}`)
  }

  if (plan.fields && plan.fields.length > 0) {
    for (const f of plan.fields) {
      if (f.agg === 'distinct_count') {
        const expr = `COUNT(DISTINCT ${quoteIdent(f.field)})`
        cols.push(f.alias ? `${expr} AS ${quoteIdent(f.alias)}` : expr)
        continue
      }
      const sqlAgg = f.agg ? aggMap[f.agg] : undefined
      if (sqlAgg) {
        const expr = `${sqlAgg}(${quoteIdent(f.field)})`
        cols.push(f.alias ? `${expr} AS ${quoteIdent(f.alias)}` : expr)
      } else {
        // Unknown or missing agg: fall back to a plain column reference so we
        // never emit 'undefined(...)' against the database.
        cols.push(
          f.alias ? `${quoteIdent(f.field)} AS ${quoteIdent(f.alias)}` : quoteIdent(f.field),
        )
      }
    }
  }

  if (cols.length === 0) return 'SELECT *'
  return `SELECT ${cols.join(', ')}`
}

function whereClause(plan: QueryPlan): string {
  if (!plan.filters || plan.filters.length === 0) return ''
  const conds = plan.filters.map((f) => {
    const col = quoteIdent(f.field)
    switch (f.op) {
      case '=':
      case '!=':
      case '>':
      case '>=':
      case '<':
      case '<=':
        return `${col} ${f.op} ${quoteValue(f.value)}`
      case 'in': {
        const vals = Array.isArray(f.value) ? f.value : [f.value]
        return `${col} IN ${quoteValue(vals)}`
      }
      case 'between': {
        const [lo, hi] = Array.isArray(f.value) ? f.value : [f.value, f.value]
        return `${col} BETWEEN ${quoteValue(lo)} AND ${quoteValue(hi)}`
      }
      case 'contains':
        return `${col} LIKE '%${String(f.value).replace(/'/g, "''")}%'`
      default:
        return `${col} = ${quoteValue(f.value)}`
    }
  })
  return `WHERE ${conds.join(' AND ')}`
}

function groupByClause(plan: QueryPlan): string {
  const parts: string[] = []
  if (plan.timeBucket) {
    parts.push(`DATE_TRUNC('${plan.timeBucket.unit}', ${quoteIdent(plan.timeBucket.field)})`)
  }
  if (plan.groupBy && plan.groupBy.length > 0) {
    for (const g of plan.groupBy) parts.push(quoteIdent(g))
  }
  if (parts.length === 0) return ''
  return `GROUP BY ${parts.join(', ')}`
}

function orderByClause(plan: QueryPlan): string {
  const specs: string[] = []
  if (plan.orderBy && plan.orderBy.length > 0) {
    for (const o of plan.orderBy) {
      specs.push(
        `${quoteIdent(o.field)} ${o.direction.toLowerCase() === 'asc' ? 'ASC' : 'DESC'}`,
      )
    }
  } else if (plan.timeBucket) {
    // Timeseries without explicit ordering: order by the bucket ascending.
    specs.push(
      `DATE_TRUNC('${plan.timeBucket.unit}', ${quoteIdent(plan.timeBucket.field)}) ASC`,
    )
  }
  if (specs.length === 0) return ''
  return `ORDER BY ${specs.join(', ')}`
}

function joinClause(plan: QueryPlan): string {
  if (!plan.joins || plan.joins.length === 0) return ''
  return plan.joins
    .map((j) => {
      const kind = j.type === 'left' ? 'LEFT JOIN' : 'INNER JOIN'
      return `${kind} ${quoteIdent(j.table)} ON ${quoteIdent(j.on.left)} = ${quoteIdent(j.on.right)}`
    })
    .join(' ')
}

export function compileToSQL(plan: QueryPlan): string {
  if (plan.entities.length === 0) return 'SELECT 1 AS placeholder'

  const parts = [selectClause(plan), `FROM ${quoteIdent(plan.entities[0])}`]
  const joins = joinClause(plan)
  const where = whereClause(plan)
  const group = groupByClause(plan)
  const order = orderByClause(plan)
  if (joins) parts.push(joins)
  if (where) parts.push(where)
  if (group) parts.push(group)
  if (order) parts.push(order)
  parts.push(`LIMIT ${Math.min(plan.limit ?? 100, 1000)}`)

  return parts.join(' ')
}

/* ─────────────────────  MongoDB aggregation pipeline  ──────────────────── */

function escapeMongoVal(value: unknown): unknown {
  if (typeof value === 'string') {
    return value.replace(/\$/g, '\uFF04').replace(/\./g, '\uFF0E')
  }
  return value
}

export function compileToMongoPipeline(plan: QueryPlan): Record<string, unknown>[] {
  const pipeline: Record<string, unknown>[] = []

  if (plan.filters && plan.filters.length > 0) {
    const match: Record<string, unknown> = {}
    for (const f of plan.filters) {
      const opMap: Record<string, string> = {
        '=': '$eq',
        '!=': '$ne',
        '>': '$gt',
        '>=': '$gte',
        '<': '$lt',
        '<=': '$lte',
        in: '$in',
      }
      if (f.op === 'between') {
        const [lo, hi] = Array.isArray(f.value) ? f.value : [f.value, f.value]
        match[f.field] = { $gte: escapeMongoVal(lo), $lte: escapeMongoVal(hi) }
        continue
      }
      if (f.op === 'contains') {
        match[f.field] = { $regex: String(f.value), $options: 'i' }
        continue
      }
      const mongoOp = opMap[f.op] ?? '$eq'
      if (mongoOp === '$in') {
        const vals = Array.isArray(f.value) ? f.value : [f.value]
        match[f.field] = { $in: vals.map(escapeMongoVal) }
      } else {
        match[f.field] = { [mongoOp]: escapeMongoVal(f.value) }
      }
    }
    pipeline.push({ $match: match })
  }

  const hasAgg = plan.fields?.some((f) => f.agg) ?? false

  if (plan.groupBy && plan.groupBy.length > 0) {
    const _id: Record<string, string> = {}
    for (const g of plan.groupBy) _id[g] = `$${g}`
    const acc: Record<string, unknown> = {}
    for (const f of plan.fields ?? []) {
      if (!f.agg) continue
      const alias = f.alias || f.field
      acc[alias] = toAccumulator(f.agg, f.field)
    }
    pipeline.push({ $group: { _id, ...acc } })
  } else if (hasAgg) {
    const acc: Record<string, unknown> = {}
    for (const f of plan.fields ?? []) {
      if (!f.agg) continue
      const alias = f.alias || f.field
      acc[alias] = toAccumulator(f.agg, f.field)
    }
    pipeline.push({ $group: { _id: null, ...acc } })
  }

  if (plan.fields && plan.fields.length > 0) {
    const project: Record<string, unknown> = { _id: 0 }
    for (const f of plan.fields) {
      const alias = f.alias || f.field
      project[alias] = plan.groupBy?.length ? `$_id.${f.field}` : `$${alias}`
    }
    if (plan.groupBy) {
      for (const g of plan.groupBy) project[g] = `$_id.${g}`
    }
    pipeline.push({ $project: project })
  }

  if (plan.orderBy && plan.orderBy.length > 0) {
    const sort: Record<string, 1 | -1> = {}
    for (const o of plan.orderBy) sort[o.field] = o.direction === 'asc' ? 1 : -1
    pipeline.push({ $sort: sort })
  }

  pipeline.push({ $limit: Math.min(plan.limit ?? 100, 1000) })
  return pipeline
}

function toAccumulator(agg: string, field: string): Record<string, unknown> {
  switch (agg) {
    case 'sum':
      return { $sum: `$${field}` }
    case 'avg':
      return { $avg: `$${field}` }
    case 'min':
      return { $min: `$${field}` }
    case 'max':
      return { $max: `$${field}` }
    case 'count':
      return { $sum: 1 }
    case 'distinct_count':
      return { $addToSet: `$${field}` }
    default:
      return { $sum: 1 }
  }
}
